const std = @import("std");
const c = @import("c_include.zig").c;

const ArrayList = std.ArrayList;

// The type for custom components. Use is not recommended if not nessecary, unsafe and unmanaged
pub const CustomComponent = struct {
    custom_type: type,
    custom: *anyopaque,
};

// Generates an entity type needed for GenerateECSType
pub fn generateEntityType(comptime count: usize) type {
    return struct {
        // count+1 to account for custom_component
        components_set: std.bit_set.StaticBitSet(count+1) = std.bit_set.StaticBitSet(count+1).initEmpty(),
   
        const Self = @This();

        pub fn addComponent(self: *Self, index: u32) void {
            self.components_set.set(index);
        }
    };
}

pub fn printHashMap(comptime K: type, comptime V: type, map: *std.AutoHashMap(K, V)) void {
    var it = map.iterator();
    while (it.next()) |entry| {
        std.debug.print("Key: {any}, Value: {any}\n", .{ entry.key_ptr.*, entry.value_ptr.* });
    }
}

// Generates a Component_Struct type for an ECS - used for GenerateECSType
pub fn GenerateComponentStructType(comptime Components: []const type) type {
    const Base_Struct = struct {
        custom_component: std.AutoHashMap(u32, *CustomComponent),
    };
    const fixed_fields: []const std.builtin.Type.StructField = @typeInfo(Base_Struct).@"struct".fields;

    var struct_fields: [fixed_fields.len+(Components.len*2)]std.builtin.Type.StructField = undefined;

    std.mem.copyForwards(std.builtin.Type.StructField, struct_fields[0..fixed_fields.len], fixed_fields);
    for (struct_fields[fixed_fields.len..fixed_fields.len+Components.len], Components) |*struct_field, t| {
        struct_field.* = .{
            .name = "component_"++@typeName(t),
            .type = std.AutoHashMap(u32, *const t),
            .default_value_ptr = null,
            .is_comptime = false,
            .alignment = @alignOf(std.AutoHashMap(u32, *t)),
        };
    }
    for (struct_fields[fixed_fields.len+Components.len..], Components) |*struct_field, t| {
        struct_field.* = .{
            .name = "rev_component_"++@typeName(t),
            .type = std.AutoHashMap(*const t, u32),
            .default_value_ptr = null,
            .is_comptime = false,
            .alignment = @alignOf(std.AutoHashMap(*t, u32)),
        };
    }

    return @Type(.{ .@"struct" = .{
        .layout = .auto,
        .fields = &struct_fields,
        .decls = &.{},
        .is_tuple = false,
    }});
}

fn getComponentTypeFromComponent(component: anytype) type {
    if (@typeInfo(@TypeOf(component)) != .pointer) {
        @compileError("Expected a pointer type");
    }
    return @typeInfo(@TypeOf(component)).pointer.child; 
}

// Generates a ECS based on the Component_Struct_Type generated by GenerateComponentStructType
pub fn GenerateECSType(comptime Entity_Type: type, comptime Component_Struct_Type: type) type {
    const ID_Manager = struct {
        next: u32 = 0,
        free: std.ArrayList(u32),

        const Self = @This();

        pub fn getNext(self: *Self) u32 {
            const last = self.free.pop();
            if (last == null) {
                self.next+=1;
                return self.next-1;
            }
            return last.?;
        }

        // Doesn't check if entity is already removed. Calling multiple times on the same entity might lead to congestion
        pub fn remove(self: *Self, entity: u32) void {
            if (entity == self.next-1) {
                self.next-=1;
                return;
            }

            self.free.append(entity) catch |err| {
                std.debug.panic("{}\n", .{err});
            };
        }
    };

    return struct {
        entity_id_manager: ID_Manager,
        component_id_manager: ID_Manager,
        entities: std.AutoHashMap(u32, *Entity_Type),
        components: Component_Struct_Type,
        
        component_index_map: std.StringHashMap(u32),

        pub fn init(comptime Components: []const type, allocator: std.mem.Allocator) !GenerateECSType(Entity_Type, Component_Struct_Type) {
            var temp = std.StringHashMap(u32).init(allocator);
            const component_types = @typeInfo(Component_Struct_Type).@"struct".fields;
            inline for (component_types) |t| {
                try temp.put(t.name, temp.count());
            }

            return .{
                .entity_id_manager = .{
                    .next = 0,
                    .free = std.ArrayList(u32).init(allocator),
                },
                .component_id_manager = .{
                    .next = 0,
                    .free = std.ArrayList(u32).init(allocator),
                },
                .entities = std.AutoHashMap(u32, *Entity_Type).init(allocator),
                .components = initComponentStruct(Component_Struct_Type, Components, allocator),
                .component_index_map = temp,
            };
        }
        
        const Self = @This();

        // Adds an entity, returns the id
        pub fn addEntity(self: *Self) u32 {
            var entity: Entity_Type = .{};
            const id = self.entity_id_manager.getNext(); 
            self.entities.put(id, &entity) catch |err| {
                std.debug.panic("{}\n", .{err});
            };
            return id;
        }

        // Removes an entity, returns true if removal was successful
        pub fn removeEntity(self: *Self, entity: u32) bool {
            const rem = self.entities.remove(entity);
            if (rem) {
                self.entity_id_manager.remove(entity);
            }
            return rem;
        }

        fn getComponentMapNameFromType(pointee_type: type) []const u8 {
            return "component_" ++ @typeName(pointee_type);
        }

        fn getComponentMapPointerFromName(self: *Self, comptime name: []const u8) *@TypeOf(@field(self.components, name)) {
            return &@field(self.components, name);
        }

        // Adds a component to a specified entity
        pub fn addComponent(self: *Self, entity: u32, comptime component: anytype) void {
            // Aquire correct map
            const pointee_type = getComponentTypeFromComponent(component);
            var component_map = self.getComponentMapPointerFromName(getComponentMapNameFromType(pointee_type));
            var rev_component_map = self.getComponentMapPointerFromName("rev_"++getComponentMapNameFromType(pointee_type));
            
            // Register new component
            const id = self.component_id_manager.getNext();
            component_map.put(id, component) catch |err| {
                std.debug.panic("{}\n", .{err});
            };
            rev_component_map.put(component, id) catch |err| {
                std.debug.panic("{}\n", .{err});
            };
            std.debug.print("{p}\n", .{component});
            
            // Register component in entity
            const index = self.component_index_map.get("component_" ++ @typeName(pointee_type)) orelse std.debug.panic("No entry in component_map for {s}\n", .{@typeName(pointee_type)});
            const e = self.entities.get(entity) orelse std.debug.panic("No entity with ID {d} exists\n", .{entity});
            e.addComponent(index);
        }

        // Removes a component from a specified entitiy
        pub fn removeComponent(self: *Self, entity: u32, comptime component: anytype) void {
            _ = entity;

            const pointee_type = getComponentTypeFromComponent(component);
            var rev_component_map = self.getComponentMapPointerFromName("rev_"++getComponentMapNameFromType(pointee_type));
            
            //printHashMap(*const pointee_type, u32, component_map);
            const id = rev_component_map.get(component) orelse std.debug.panic("The component {p} is not registered\n", .{component});
            if (!rev_component_map.remove(component)) {
                std.debug.panic("Entitiy {d} not assicated with component {p} in backwards map\n", .{id, component});
            }
            
            var component_map = self.getComponentMapPointerFromName(getComponentMapNameFromType(pointee_type));
            if (!component_map.remove(id)) {
                std.debug.panic("Entitiy {d} not assicated with component {p} in forwards map\n", .{id, component});
            }
        }
    };
}

pub fn initComponentStruct(comptime ECS_Component_Struct_Type: type, comptime Components: []const type, allocator: std.mem.Allocator) ECS_Component_Struct_Type {
    var comp_struct: ECS_Component_Struct_Type = undefined;
    @field(comp_struct, "custom_component") = std.AutoHashMap(u32, *CustomComponent).init(allocator);
    inline for (Components) |comp| {
        @field(comp_struct, "component_"++@typeName(comp)) = std.AutoHashMap(u32, *const comp).init(allocator);
    }
    inline for (Components) |comp| {
        @field(comp_struct, "rev_component_"++@typeName(comp)) = std.AutoHashMap(*const comp, u32).init(allocator);
    }

    return comp_struct;
}

//pub fn initECS(comptime ECS_Type: type, comptime Entitiy_Type: type, comptime Components: []const type, allocator: std.mem.Allocator) ECS_Type {
//    const temp: ECS_Type = undefined;
//    return .{
//        .entity_id_manager = .{
//            .free = std.ArrayList(u32).init(allocator),
//        },
//        .component_id_manager = .{
//            .free = std.ArrayList(u32).init(allocator),
//        },
//        .entities = std.AutoHashMap(u32, *Entitiy_Type).init(allocator),
//        .components = initComponentStruct(@TypeOf(temp.components), Components, allocator),
//    };
//
//}
