const std = @import("std");
const c = @import("c_include.zig").c;

const ArrayList = std.ArrayList;

// The type for custom components. Use is not recommended if not nessecary, unsafe and unmanaged
pub const CustomComponent = struct {
    custom_type: type,
    custom: *anyopaque,
};

// Generates an entity type needed for GenerateECSType
pub fn generateEntityType(comptime count: usize) type {
    return struct {
        components_set: std.bit_set.StaticBitSet(count) = std.bit_set.StaticBitSet(count).initEmpty(),
   
        const Self = @This();

        pub fn addComponent(self: *Self) void {
            _ = self;
        }
    };
}

// Generates a Component_Struct type for an ECS - used for GenerateECSType
pub fn GenerateComponentStructType(comptime Components: []const type) type {
    const Base_Struct = struct {
        custom_component: std.AutoHashMap(u32, *CustomComponent),
    };
    const fixed_fields: []const std.builtin.Type.StructField = @typeInfo(Base_Struct).@"struct".fields;

    var struct_fields: [fixed_fields.len+Components.len]std.builtin.Type.StructField = undefined;

    std.mem.copyForwards(std.builtin.Type.StructField, struct_fields[0..fixed_fields.len], fixed_fields);
    for (struct_fields[fixed_fields.len..], Components) |*struct_field, t| {
        struct_field.* = .{
            .name = "component_"++@typeName(t),
            .type = std.AutoHashMap(u32, *t),
            .default_value_ptr = null,
            .is_comptime = false,
            .alignment = @alignOf(std.AutoHashMap(u32, *t)),
        };
    }

    return @Type(.{ .@"struct" = .{
        .layout = .auto,
        .fields = &struct_fields,
        .decls = &.{},
        .is_tuple = false,
    }});
}

// Generates a ECS based on the Component_Struct_Type generated by GenerateComponentStructType
pub fn GenerateECSType(comptime Entity_Type: type, comptime Component_Struct_Type: type) type {
    const ID_Manager = struct {
        next: u32 = 0,
        free: std.ArrayList(u32),

        const Self = @This();

        pub fn getNext(self: *Self) u32 {
            const last = self.free.pop();
            if (last == null) {
                self.next+=1;
                return self.next-1;
            }
            return last.?;
        }

        // Doesn't check if entity is already removed. Calling multiple times on the same entity might lead to congestion
        pub fn remove(self: *Self, entity: u32) void {
            if (entity == self.next-1) {
                self.next-=1;
                return;
            }

            self.free.append(entity) catch |err| {
                std.debug.panic("{}\n", .{err});
            };
        }
    };

    return struct {
        entity_id_manager: ID_Manager,
        component_id_manager: ID_Manager,
        entities: std.AutoHashMap(u32, *Entity_Type),
        components: Component_Struct_Type,
        
        component_map: std.StringHashMap(u32),

        pub fn init(comptime Components: []const type, allocator: std.mem.Allocator) !GenerateECSType(Entity_Type, Component_Struct_Type) {
            var temp = std.StringHashMap(u32).init(allocator);
            const component_types = @typeInfo(Component_Struct_Type).@"struct".fields;
            inline for (component_types) |t| {
                try temp.put(t.name, temp.count());
            }

            return .{
                .entity_id_manager = .{
                    .next = 0,
                    .free = std.ArrayList(u32).init(allocator),
                },
                .component_id_manager = .{
                    .next = 0,
                    .free = std.ArrayList(u32).init(allocator),
                },
                .entities = std.AutoHashMap(u32, *Entity_Type).init(allocator),
                .components = initComponentStruct(Component_Struct_Type, Components, allocator),
                .component_map = temp,
            };
        }
        
        const Self = @This();

        // Adds an entity, returns the id
        pub fn addEntity(self: *Self) u32 {
            var entity: Entity_Type = .{};
            const id = self.entity_id_manager.getNext(); 
            self.entities.put(id, &entity) catch |err| {
                std.debug.panic("{}\n", .{err});
            };
            return id;
        }

        // Removes an entity, returns true if removal was successful
        pub fn removeEntity(self: *Self, entity: u32) bool {
            const rem = self.entities.remove(entity);
            if (rem) {
                self.entity_id_manager.remove(entity);
            }
            return rem;
        }

        // Adds a component to a specified entity
        pub fn addComponent(self: *Self, entity: Entity_Type, component: anytype) void {
            const comp_name = "component_" ++ @typeName(component);
            const id = self.component_id_manager.getNext();
            @field(self.components, comp_name).put(id, component) catch |err| {
                std.debug.panic("{}\n", .{err});
            };
            _ = entity;
            //entity.
        }
    };
}

pub fn initComponentStruct(comptime ECS_Component_Struct_Type: type, comptime Components: []const type, allocator: std.mem.Allocator) ECS_Component_Struct_Type {
    var comp_struct: ECS_Component_Struct_Type = undefined;
    @field(comp_struct, "custom_component") = std.AutoHashMap(u32, *CustomComponent).init(allocator);
    inline for (Components) |comp| {
        @field(comp_struct, "component_"++@typeName(comp)) = std.AutoHashMap(u32, *comp).init(allocator);
    }

    return comp_struct;
}

//pub fn initECS(comptime ECS_Type: type, comptime Entitiy_Type: type, comptime Components: []const type, allocator: std.mem.Allocator) ECS_Type {
//    const temp: ECS_Type = undefined;
//    return .{
//        .entity_id_manager = .{
//            .free = std.ArrayList(u32).init(allocator),
//        },
//        .component_id_manager = .{
//            .free = std.ArrayList(u32).init(allocator),
//        },
//        .entities = std.AutoHashMap(u32, *Entitiy_Type).init(allocator),
//        .components = initComponentStruct(@TypeOf(temp.components), Components, allocator),
//    };
//
//}
